package entities.macros;

#if macro

import entities.macros.helpers.ClassBuilder;
import entities.macros.helpers.ClassVariable;

class ClassBuilderTools {
    public static function isEntity(classBuilder:ClassBuilder):Bool {
        return classBuilder.hasInterface("entities.IEntity");
    }

    public static function tableName(classBuilder:ClassBuilder, lowerCase:Bool = true) {
        var tableName = classBuilder.name;
        if (lowerCase) {
            tableName = tableName.toLowerCase();
        }
        if (classBuilder.metadata.contains("table")) {
            tableName = classBuilder.metadata.paramAsString("table");
        }
        return tableName;
    }

    public static function primaryKeyField(classBuilder:ClassBuilder):ClassVariable {
        if (classBuilder.metadata.contains("primaryKey")) {
            var primaryKeyName = classBuilder.metadata.paramAsString("primaryKey");
            var primaryKeyField = classBuilder.findVar(primaryKeyName);
            return primaryKeyField;
        }

        for (f in classBuilder.vars) {
            if (f.metadata.contains("primaryKey")) {
                return f;
            }
        }

        return null;
    }

    public static function primaryKeyFieldName(classBuilder:ClassBuilder):String {
        return autoGeneratedPrimaryKeyName(classBuilder);
    }

    public static function autoGeneratedPrimaryKeyName(classBuilder:ClassBuilder):String {
        var tableName = tableName(classBuilder, false);
        return tableName.substr(0, 1).toLowerCase() + tableName.substr(1) + "Id";
    }
}

#end