package entities.macros;

#if macro
import entities.macros.helpers.ClassBuilder;

using entities.macros.ClassBuilderTools;
using entities.macros.ClassVariableTools;
using StringTools;
#end

class EntityBuilderTools {
    #if macro
    public static function checkForPrimaryKeys(entityClass:ClassBuilder, entityDefinition:EntityDefinition) {
        var primaryKeyField = entityClass.primaryKeyField();
        if (primaryKeyField == null) {
            primaryKeyField = entityClass.addVar(entityClass.autoGeneratedPrimaryKeyName(), 0);
            if (!entityClass.isExtern) {
                primaryKeyField.complexType = macro: Null<Int>;
            }
            primaryKeyField.isPublic = entityClass.metadata.contains(EntityMetadata.ExposeId);
        }

        primaryKeyField.metadata.add(EntityMetadata.PrimaryKey);
        primaryKeyField.metadata.add(EntityMetadata.AutoIncrement);
        entityDefinition.primaryKeyFieldAutoIncrement = true;
        entityDefinition.primaryKeyFieldName = primaryKeyField.name;
        entityDefinition.primaryKeyFieldType = primaryKeyField.toEntityFieldType();
    }
    #end
    
}